### PR TITLE
fix(form-core) sync autofocus to focusable node (fixes #1775)

### LINKED ISSUE #1775: [form-core] Lion form field components do not receive autofocus in dialog
## Expected behavior

When adding a lion-input with autofocus to a lion-dialog, on opening the dialog it should put initial focus on the lion-input.

See the following [code-example](https://studio.webcomponents.dev/edit/oCJHLBB0uzh4K3uas5Au/README.md?p=README.md) where the fourth button highlight the autofocus bug.

## Actual Behavior

The initial focus goes to the dialog element.

## Additional context

Package form-core version 0.18.3.
This bug was found while trying to find a workaround for a [bug in safari with the dialog](https://github.com/ing-bank/lion/issues/1773).

### Cause of the issue
The issue is caused by the implementation of intial focus in [contain-focus.js](https://github.com/ing-bank/lion/blob/650657231a4ec83592d45cd69836d28436635340/packages/overlays/src/utils/contain-focus.js#L74) where intial focus is set to the first focuasable element with the autofocus attribute, or the dialog element. While this is a fine implementation for native html elements, it fails when using lion form field components as from the outside it is hard to set autofocus on the input element. Setting autofocus on the component does not work as the component itself is not focusable, so is not accounted for when determining inital focus.

### Use case
While inappropriate use of the autofocus attribute can lead to bad user experience, especially for screen reader users. There are use cases for the dialog, like a confirmation dialog, where it can improve the user experience by immediately focussing the primary button, or a dialog containing a form where the first form field is focused. As long as the text content above the button/form field is linked to the dialog via aria-describedby this as a valid and accessible way to setup a dialog.

### PR DESCRIPTION
**Pull request by Sciurus7**
## What I did

1. In FocusMixin synced the autofocus attribute from the host to the focusable node.
2. Added tests to ensure the sync happens if autofocus was set on the host during render or when autofocus is added or removed from the host.

### CODE REVIEW

File: packages/ui/components/form-core/src/FocusMixin.js [hunk 1]
```diff
@@ -52,13 +53,43 @@ const FocusMixinImplementation = superclass =>
...
+    /**
+     * @private
+     */
+    __syncAutofocusToFocusableElement() {
+      if (!this._focusableNode) {
+        return;
+      }
+
+      if (this.hasAttribute('autofocus')) {
+        this._focusableNode.setAttribute('autofocus', '');
```
Comment (tlouisse) [inline packages/ui/components/form-core/src/FocusMixin.js:87]: Hey, nice PR :)

Could this be tested in an integration test with our dialog system as well?

The spec says:
>No more than one element in the document or dialog may have the autofocus attribute. If  applied to multiple elements the first one will receive focus.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus

Since recently we [use a native `<dialog>`](https://github.com/ing-bank/lion/pull/1712) under the hood.
I suspect that if both the host and _focusableNode have focus, the platform might attempt to put focus on the parent element (in case we don't configure the OverlayController with `trapsKeyboardFocus: true`, in which case [it calls contain-focus, like mentioned here](https://github.com/ing-bank/lion/pull/1776#event-9007140697))

Could we rule this out via an integration test in the overlay system?

File: packages/ui/components/form-core/src/FocusMixin.js [hunk 2]
```diff
@@ -52,13 +53,43 @@ const FocusMixinImplementation = superclass =>
...
     }
 
+    /**
+     * Gets called when an attribute is changed.
+     * @param {String} name
+     * @param {String | null} _old
+     * @param {String | null} value
+     * @protected
+     */
+    attributeChangedCallback(name, _old, value) {
```
Comment (tlouisse) [inline packages/ui/components/form-core/src/FocusMixin.js:71]: Is there a particular reason to use attributeChangedCallback? 
Not necessarily wrong ofc, but we usually rely on the `updated` callback from lit for perf/consistency

File: packages/ui/components/form-core/types/FocusMixinTypes.ts [hunk 3]
```diff
@@ -25,6 +25,12 @@ export declare class FocusHost {
    */
   blur(): void;
 
+  /**
+  * Synchronizes property values when attributes change.
+  * @category attributes
+  */
+    attributeChangedCallback(name: string, _old: string | null, value: string | null): void;
```
Comment (tlouisse) [inline packages/ui/components/form-core/types/FocusMixinTypes.ts:32]: Was TS complaining about it? I expect this to be already available on HTMLElement, which LItElement inherits from

File: packages/ui/components/form-core/src/FocusMixin.js (hunk 2 above)
Comment (Sciurus7) [reply packages/ui/components/form-core/src/FocusMixin.js]: Hi @tlouisse, honestly it's been a while since I actually created the original pull request, so I'm not quite sure why I decided to go with attributeChangedCallback. My suspicion would be, that, as we're dealing with an attribute this felt like the more appropriate place to listen to the change. That being said I've tested the change with updated and it works just as well, so I've added a commit using the updated, this also means the change to FocusMixinTypes is not required anymore.

File: packages/ui/components/form-core/src/FocusMixin.js (hunk 1 above)
Comment (Sciurus7) [reply packages/ui/components/form-core/src/FocusMixin.js:84]: Hi Thijs, good point. I've tried to write a test for what happens if "trapsKeyboardFocus: false" is set. 
The good news is that it won't focus the host. The potentially bad news is that it will not focus the _focusableNode either. 

I've done some manual testing on the desktop versions of Firefox, Chromium and Safari and found the following. In all cases I tested with autofocus synced: 

1. Test case: A LionDialog with trapsKeyboardFocus set to true and an LionCheckbox with autofocus. Result: The focusable node was focused.
2. Test

If trapsKeyboardFocus is set to true autofocus works as intended. If trapsKeyboardFocus is set to false autofocus will not work, pressing tab once will set the focus to the first focusable element in the dialog. 
This holds true both for a LionField with autofocus or a native html input with autofocus. Using a LionField with autofocus in a native dialog will focus the focusable_node, not the host

Comment (gerjanvangeest) [reply packages/ui/components/form-core/src/FocusMixin.js:84]: Yes indeed for nr 2. Its not a new page, so the focus stays where it is.

I've added some focus tests to the dialog and form-integration.

Comment (tlouisse) [reply packages/ui/components/form-core/src/FocusMixin.js:84]: Hey @Sciurus7 , thanks for all the great help and testing this. Sorry that I postponed my repsonse (wanted to test some things in the browser but didn't get to it...)
Luckily Gerjan took over so I'm happy to merge this :)

**Review by Knorgias — APPROVED** [review]
