### PR TITLE
fix(tabs): tab keyboard navigation trap

### LINKED ISSUE #712: [tabs] trapped in tabs when focused
## Describe the bug

Tab is a trap!

When navigating with keyboard on tabs, you can't leave them with keyboard

## To Reproduce

1. Go to https://lion-web-components.netlify.app/?path=/story/navigation-tabs--default-story
2. Click on first tab
3. Try to navigate to anything else with _Tab_ key
4. You're trapped

## Expected behavior

Only arrow keys should be trapped

### PR DESCRIPTION
**Pull request by MathieuPuech**
Closes #712

### CODE REVIEW

File: packages/tabs/src/LionTabs.js [hunk 1]
```diff
@@ -51,6 +51,17 @@ const deselectButton = element => {
   element.setAttribute('tabindex', -1);
 };
 
+const handleButtonKeydown = e => {
+  switch (e.key) {
+    case 'ArrowDown':
+    case 'ArrowRight':
+    case 'ArrowUp':
+    case 'ArrowLeft':
+      e.preventDefault();
```
Comment (gerjanvangeest) [inline packages/tabs/src/LionTabs.js:60]: I'm missing `home` & `end`.

File: packages/tabs/src/LionTabs.js [hunk 2]
```diff
@@ -168,7 +180,7 @@ export class LionTabs extends LitElement {
     };
   }
 
-  __handleButtonKeydown(e) {
+  __handleButtonKeyup(e) {
     switch (e.key) {
       case 'ArrowDown':
       case 'ArrowRight':
```
Comment (gerjanvangeest) [inline packages/tabs/src/LionTabs.js:186]: I believe all `e.preventDefault`s can be removed from the keyup handler
